# This is a basic workflow to help you get started with Actions

name: Combined_CI_V2

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow creates a VM labeled `matlab_linux`
  create_runner:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Don't run if we ask to skip CI
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Creates the new VM
      - name: Invoke creation hook
        uses: distributhor/workflow-webhook@v1
        env:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          webhook_auth: ${{ secrets.WEBHOOK_AUTH }}
          data: '{ "ghcontrol": "create", "server" : "linux", "PAT" : "${{ secrets.PERSONAL_TOKEN }}" }'
  
  # This workflow runs the actual unit tests if we have suceeded creating the VM
  unit_tests:
    needs: create_runner
    # The type of runner that the job will run on
    runs-on: linux_matlab

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs MATLAB tests
      - name: Run Matlab
        run: matlab -batch "run run_tests.m"
      # Upload the results
      - uses: codecov/codecov-action@v1
        with:
            files: coverage.xml
            token: ${{ secrets.CODECOV_TOKEN }}
          
  # This workflow always runs after the creating and unit tests, destroying the VM
  destroy_runner:
    needs: [create_runner, unit_tests]
    if: always()
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Destroy the VM
      - name: Invoke destroying hook
        uses: distributhor/workflow-webhook@v1
        env:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          webhook_auth: ${{ secrets.WEBHOOK_AUTH }}
          data: '{ "ghcontrol": "destroy", "server" : "linux" }'
